version: "3.8"

services:
  postgres:
    image: postgres:15
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/graalvm/postgres
    ports:
      - "5432:5432"
    networks:
      - webnet

  graalvm:
    image: hoangphucdvl/graalvm-checkpoint:checkpoint
    cap_add:
      - CHECKPOINT_RESTORE
      - SYS_ADMIN
    environment:
      - POSTGRE_URL=jdbc:postgresql://postgres:5432/postgres
      - POSTGRE_URL_PASSWORD=postgres
      - POSTGRE_URL_USERNAME=postgres
    ports:
      - "8080:8080"
    networks:
      - webnet

networks:
  webnet:

volumes:
  postgres: